workflows:
  flutter-build:
    name: Flutter Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_NAME: "MyFlutterApp"
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build Android App Bundle (AAB)
        script: flutter build appbundle --release

      - name: Build iOS app (IPA)
        script: flutter build ipa --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - you@example.com
