workflows:
  mobile-unsigned-build:
    name: Mobile Only (APK + IPA)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: 获取 Flutter 依赖
        script: flutter pub get

      - name: 构建 Android APK
        script: flutter build apk --release

      - name: 构建 iOS Runner.app（未签名）
        script: flutter build ios --release --no-codesign

      - name: 打包为 unsigned.ipa（可安装）
        script: |
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -r unsigned.ipa Payload
          rm -rf Payload build/ios/iphoneos/Runner.app  # ❌ 删除中间产物 .app

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - unsigned.ipa
